In [22]:
#!pip install pandas
#!pip install numpy
#!pip install openpyxl

In [23]:
import pandas as pd
import numpy as np
import re

In [46]:
def unicode_to_symbols(encoded_string):
    pattern = re.compile(r'_x([0-9A-Fa-f]{4})_')
    def replace_with_char(match):
        # Convert the hexadecimal value to an integer, then to the corresponding Unicode character
        return chr(int(match.group(1), 16))
    # Replace all occurrences of encoded Unicode with their corresponding characters
    return pattern.sub(replace_with_char, encoded_string)

In [42]:
unicode_to_symbols("_x0031_06")

'_x0031_06'

In [25]:
#import housing data
housing_df = pd.read_excel('housing.xlsx')

/Users/bofuzou/anaconda3/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [26]:
#import education data
education_df = pd.read_excel('education.xlsx')

In [27]:
# check for column names
housing_df.columns
education_df.columns

Index(['ind_id', 'ind_definition', 'reportyear', 'race_eth_code',
       'race_eth_name', 'geotype', 'geotypevalue', 'geoname', 'county_name',
       'county_fips', 'region_name', 'region_code', 'strata_one_code',
       'strata_one_name', 'strata_two_code', 'strata_two_name', 'numerator',
       'denominator', 'estimate', 'LL_95CI', 'UL_95CI', 'SE', 'RSE',
       'CA_decile', 'CA_RR', 'version'],
      dtype='object')

In [28]:
#filter down the columns into what we need
new_housing_df = housing_df.get(['ind_id', 'ind_definition','burden', 'geotype', 'income_level','geotypevalue', 'geoname', 'region_name','region_code'])

In [29]:
# filter to include only >50% burden
new_housing_df = new_housing_df[(new_housing_df['burden'] == '_x003E__x0020_50_x0025__x0020_of_x0020_monthly_x0020_household_x0020_income_x0020_consumed_x0020_by_x0020_monthly_x002C__x0020_selected_x002C__x0020_housing_x0020_costs')]

In [30]:
#filter out NA values and filter income
new_housing_df = new_housing_df.dropna()
new_housing_df = new_housing_df[(new_housing_df['income_level'] == 'All_x0020_income_x0020_levels') 
                              | (new_housing_df['income_level'] == 'Monthly_x0020_household_x0020_income_x0020_at_x0020_all_x0020_levels_x0020_of_x0020_HUD-adjusted_x0020_family_x0020_median_x0020_income')]
new_housing_df.head(10)

,ind_id,ind_definition,burden,geotype,income_level,geotypevalue,geoname,region_name,region_code
57,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,Monthly_x0020_household_x0020_income_x0020_at_...,_x0030_1,Bay_x0020_Area,Bay_x0020_Area,_x0030_1
67,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,All_x0020_income_x0020_levels,_x0030_1,Bay_x0020_Area,Bay_x0020_Area,_x0030_1
73,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,All_x0020_income_x0020_levels,_x0030_1,Bay_x0020_Area,Bay_x0020_Area,_x0030_1
79,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,All_x0020_income_x0020_levels,_x0030_1,Bay_x0020_Area,Bay_x0020_Area,_x0030_1
85,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,All_x0020_income_x0020_levels,_x0030_1,Bay_x0020_Area,Bay_x0020_Area,_x0030_1
91,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,All_x0020_income_x0020_levels,_x0030_1,Bay_x0020_Area,Bay_x0020_Area,_x0030_1
97,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,All_x0020_income_x0020_levels,_x0030_1,Bay_x0020_Area,Bay_x0020_Area,_x0030_1
103,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,All_x0020_income_x0020_levels,_x0030_1,Bay_x0020_Area,Bay_x0020_Area,_x0030_1
111,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,Monthly_x0020_household_x0020_income_x0020_at_...,_x0030_2,Butte,Butte,_x0030_2
121,_x0031_06,Percent_x0020_of_x0020_households_x0020_spendi...,_x003E__x0020_50_x0025__x0020_of_x0020_monthly...,RE,All_x0020_income_x0020_levels,_x0030_2,Butte,Butte,_x0030_2

In [54]:
new_new_housing_df = new_housing_df.applymap(unicode_to_symbols)
new_new_housing_df

,ind_id,ind_definition,burden,geotype,income_level,geotypevalue,geoname,region_name,region_code
57,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,RE,Monthly household income at all levels of HUD-...,01,Bay Area,Bay Area,01
67,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,RE,All income levels,01,Bay Area,Bay Area,01
73,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,RE,All income levels,01,Bay Area,Bay Area,01
79,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,RE,All income levels,01,Bay Area,Bay Area,01
85,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,RE,All income levels,01,Bay Area,Bay Area,01
...,...,...,...,...,...,...,...,...,...
521235,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,PL,All income levels,86804,Yolo CDP,Sacramento Area,08
521241,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,PL,All income levels,86804,Yolo CDP,Sacramento Area,08
521247,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,PL,All income levels,86804,Yolo CDP,Sacramento Area,08
521253,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,PL,All income levels,86804,Yolo CDP,Sacramento Area,08
521259,106,Percent of households spending more than 30% (...,> 50% of monthly household income consumed by ...,PL,All income levels,86804,Yolo CDP,Sacramento Area,08

In [1]:
#remove unnecessary columns
new_education_df = education_df.get(['ind_id', 'ind_definition', 'estimate', 'geotype', 'geotypevalue', 'geoname','region_name', 'region_code'])

NameError: name 'education_df' is not defined

In [32]:
# drop NA from education
new_education_df = new_education_df.dropna()
new_education_df.head(10)

,ind_id,ind_definition,geotype,geotypevalue,geoname,region_name,region_code
9,355,Percent of population age 25 and up with a fou...,CD,607192260,Ontario CCD,Southern California,14.0
10,355,Percent of population age 25 and up with a fou...,CD,603593280,Susanville CCD,Northeast Sierra,6.0
11,355,Percent of population age 25 and up with a fou...,CD,607192100,Newberry-Baker CCD,Southern California,14.0
12,355,Percent of population age 25 and up with a fou...,CD,609792940,Santa Rosa CCD,Bay Area,1.0
13,355,Percent of population age 25 and up with a fou...,CD,600190020,Alameda CCD,Bay Area,1.0
14,355,Percent of population age 25 and up with a fou...,CD,603790310,Calabasas CCD,Southern California,14.0
15,355,Percent of population age 25 and up with a fou...,CD,600190200,Berkeley CCD,Bay Area,1.0
16,355,Percent of population age 25 and up with a fou...,CD,603791120,Glendale CCD,Southern California,14.0
17,355,Percent of population age 25 and up with a fou...,CD,607791870,Manteca CCD,San Joaquin Valley,10.0
18,355,Percent of population age 25 and up with a fou...,CD,603791750,Los Angeles CCD,Southern California,14.0

In [33]:
#export dataframes to excel files
new_housing_df.to_excel('clean_housing.xlsx')
new_education_df.to_excel('clean_education.xlsx')

In [34]:
def unicode_to_symbols(text):
    unicode_literal_pattern = r'_u([0-9A-Fa-f]{4})'
    
    def replace_with_symbol(match):
        # Convert the hexadecimal value to an integer, then to the corresponding character
        return chr(int(match.group(1), 16))
    
    # Replace all occurrences of Unicode literals with their corresponding symbols
    return re.sub(unicode_literal_pattern, replace_with_symbol, text)